### ISSUE TITLE
Grunt test error on Maven clean

### ISSUE THREAD

**Issue by flavioayres** [IHTSDO/authoring-ui#1]
Hello, I am trying to maven install the project, but I am getting the folllowing error:

`[INFO] --------------------------------------
[INFO]          GRUNT TEST --NO-COLOR
[INFO] --------------------------------------
(node:20689) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Running "clean:server" (clean) task
>> 0 paths cleaned.

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "wiredep:sass" (wiredep) task

Running "concurrent:test" (concurrent) task
    Warning: (node:20698) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead. Use --force to continue.
        
        Aborted due to warnings.`

And also:

`[ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.2:build (run-grunt) on project authoring-ui: Error during : grunt 
test --no-color: Process exited with an error: 6 (Exit value: 6) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.2:build (run-grunt
) on project authoring-ui: Error during : grunt test --no-color
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error during : grunt test --no-color
        at com.github.trecloux.yeoman.YeomanMojo.executeCommand(YeomanMojo.java:104)
        at com.github.trecloux.yeoman.YeomanMojo.logAndExecuteCommand(YeomanMojo.java:85)
        at com.github.trecloux.yeoman.YeomanMojo.grunt(YeomanMojo.java:73)
        at com.github.trecloux.yeoman.YeomanMojo.execute(YeomanMojo.java:56)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 6 (Exit value: 6)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
        at com.github.trecloux.yeoman.YeomanMojo.executeCommand(YeomanMojo.java:102)
        ... 25 more`

Do you know what I might be doing wrong?

**Comment by Chris-Swires** [comment]
Hi @flavioayres 

Currently the test suite in the project is neither maintained or useful. A ticket has been raised to remove them from the grunt build up until the point that they can be brought up to speed. 

In the meantime please run the build without the tests in order to complete successfully. 

Thanks

**Comment by Chris-Swires** [comment]
For reference you can skip the tests using the flag 'maven.test.skip=true' 

Thanks
